apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "backstage-dotnet-api-demo"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  lifecycle: experimental
  type: service
  owner: "group:default/customer-squad"
